name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '42 5 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Thanks for the issue! This issue is being closed due to inactivity. If this is still an issue, please create a new issue and ensure the template is fully filled out.'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
